apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app-2
  description: Python app that dislpays time. - named python-app-2
  annotations:
   github.com/project-slug: henoc-tshims/python-app-2
   backstage.io/techdocs-ref: dir:.

spec:
  type: service
  owner: development
  lifecycle: experimental
